logging:
  level:
    root: INFO
    skillmanagement: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

metrics:
  employees:
    total:
      update:
        rate: "PT1M"
        delay: "PT10S"
  projects:
    total:
      update:
        rate: "PT1M"
        delay: "PT10S"
  skills:
    total:
      update:
        rate: "PT1M"
        delay: "PT10S"

storage:
  database:
    jdbc-url: "jdbc:postgresql://localhost:5432/database"
    username: user
    password: password
  elasticsearch:
    schema: http
    host: localhost
    port: 9200

spring:
  datasource:
    url: ${storage.database.jdbc-url}
    username: ${storage.database.username}
    password: ${storage.database.password}
  flyway:
    locations: "classpath:db/migration/{vendor}"
